app.frontend-url=https://test.immohorizon.com
app.backend-url=https://api-test.immohorizon.com

stripe.secret-key=${STRIPE_TEST_SECRET_KEY}

spring.datasource.url=jdbc:mysql://test-database:3306/immohorizon
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}