app.frontend-url=http://immohorizon-demo.s3-website-us-east-1.amazonaws.com/
app.backend-url=https://api.immohorizon.com
stripe.secret-key=${STRIPE_SECRET_KEY}
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.port=3030
jwt.secret=${JWT_SECRET}