export enum etats{
     DISPONIBLE = 'DISPONIBLE',
  VENDU = 'VENDU',
  LOUE = 'LOUE',
  SOUS_OPTION = 'SOUS_OPTION',
  EN_MAINTENANCE = 'EN_MAINTENANCE',
  EN_FIN_DE_LOCATION = 'EN_FIN_DE_LOCATION',
  ARCHIVE = 'ARCHIVE'};