export enum TypeChauffage {
  GAZ = 'GAZ',
  MAZOUT = 'MAZOUT',
  ELECTRIQUE = 'ELECTRIQUE',
  POMPE_A_CHALEUR = 'POMPE_A_CHALEUR',
  BOIS = 'BOIS',
  PELLETS = 'PELLETS',
  CHARBON = 'CHARBON',
  SOLAIRE = 'SOLAIRE',
  GEOTHERMIE = 'GEOTHERMIE',
  RESEAU_DE_CHALEUR = 'RESEAU_DE_CHALEUR',
  MIXTE = 'MIXTE',
  AUCUN = 'AUCUN',
  AUTRE = 'AUTRE'
}