export enum typesDeBien{
   APPARTEMENT= "APPARTEMENT",
   MAISON= "MAISON",
   STUDIO="STUDIO",
   DUPLEX= "DUPLEX",
    LOFT="LOFT",
    VILLA="VILLA",
    TERRAIN="TERRAIN",
    BUREAU="BUREAU",
    COMMERCE="COMMERCE",
    ENTREPOT="ENTREPOT",
    PARKING="PARKING",
    LOCAL_COMMERCIAL="LOCAL_COMMERCIAL",
    IMMEUBLE="IMMEUBLE"
}
    
