name: CD WORKFLOW - Deploy Angular to S3

on:
  workflow_run:
    workflows: ["Docker CI"]
    types:
      - completed

# Required for GitHub OIDC
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:

      - name: Pull latest Docker image
        run: |
          docker pull ruthann33/immohorizon-frontend:latest

      - name: Remove old container
        run: |
          docker rm -f immohorizon-frontend || true

      - name: Create temporary container
        run: |
          docker create \
            --name immohorizon-frontend \
            ruthann33/immohorizon-frontend:latest

      - name: Copy Angular files from Docker image
        run: |
          rm -rf ./angular-dist
          mkdir -p ./angular-dist

          docker cp \
            immohorizon-frontend:/usr/share/nginx/html/. \
            ./angular-dist/

      # Authenticate to AWS using GitHub OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654452332313:role/ImmoHorizonGitHubActions
          aws-region: us-east-1

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      - name: Deploy Angular to S3
        run: |
          aws s3 sync \
            ./angular-dist/ \
            s3://immohorizon-demo/ \
            --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

      - name: Remove temporary container
        run: |
          docker rm -f immohorizon-frontend || true