name: Deploy to EC2
on:
  push:
    branches:
      - dev/backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            cd ~/immohorizon
          
            docker pull ruthann33/immohorizon-backend:latest
          
            docker stop immohorizon-backend || true
            docker rm immohorizon-backend || true
          
            docker run -d \
            --name immohorizon-backend \
            --restart unless-stopped \
            -p 3030:3030 \
            --env-file ~/immohorizon/.env \
            ruthann33/immohorizon-backend:latest
          
            docker ps